// <auto-generated />
using System;
using DeepWiki.Data.SqlServer.DbContexts;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeepWiki.Data.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerVectorDbContext))]
    [Migration("20260301194915_AddWikiTables")]
    partial class AddWikiTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("IX_Wikis_CollectionId");

                    b.ToTable("Wikis", (string)null);
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectionPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WikiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentPageId");

                    b.HasIndex("SectionPath")
                        .HasDatabaseName("IX_WikiPages_SectionPath");

                    b.HasIndex("WikiId")
                        .HasDatabaseName("IX_WikiPages_WikiId");

                    b.ToTable("WikiPages", (string)null);
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageRelation", b =>
                {
                    b.Property<Guid>("SourcePageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetPageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourcePageId", "TargetPageId");

                    b.HasIndex("TargetPageId")
                        .HasDatabaseName("IX_WikiPageRelations_TargetPageId");

                    b.ToTable("WikiPageRelations", (string)null);
                });

            modelBuilder.Entity("DeepWiki.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChunkIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<SqlVector<float>?>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsImplementation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(1048576)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalChunks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Documents_CreatedAt");

                    b.HasIndex("RepoUrl")
                        .HasDatabaseName("IX_Documents_RepoUrl");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", b =>
                {
                    b.HasOne("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("ParentPageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_WikiPages_ParentPageId");

                    b.HasOne("DeepWiki.Data.Abstractions.Entities.WikiEntity", "Wiki")
                        .WithMany("Pages")
                        .HasForeignKey("WikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WikiPages_WikiId");

                    b.Navigation("ParentPage");

                    b.Navigation("Wiki");
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageRelation", b =>
                {
                    b.HasOne("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", "SourcePage")
                        .WithMany("SourceRelations")
                        .HasForeignKey("SourcePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WikiPageRelations_SourcePageId");

                    b.HasOne("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", "TargetPage")
                        .WithMany("TargetRelations")
                        .HasForeignKey("TargetPageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_WikiPageRelations_TargetPageId");

                    b.Navigation("SourcePage");

                    b.Navigation("TargetPage");
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiEntity", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", b =>
                {
                    b.Navigation("ChildPages");

                    b.Navigation("SourceRelations");

                    b.Navigation("TargetRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
