// <auto-generated />
using System;
using DeepWiki.Data.Postgres.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace DeepWiki.Data.Postgres.Migrations
{
    [DbContext(typeof(PostgresVectorDbContext))]
    [Migration("20260301194738_AddWikiTables")]
    partial class AddWikiTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_wikis_collection_id");

                    b.ToTable("wikis", (string)null);
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ParentPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_page_id");

                    b.Property<string>("SectionPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("section_path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WikiId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiki_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentPageId");

                    b.HasIndex("SectionPath")
                        .HasDatabaseName("ix_wiki_pages_section_path");

                    b.HasIndex("WikiId")
                        .HasDatabaseName("ix_wiki_pages_wiki_id");

                    b.ToTable("wiki_pages", (string)null);
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageRelation", b =>
                {
                    b.Property<Guid>("SourcePageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_page_id");

                    b.Property<Guid>("TargetPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_page_id");

                    b.HasKey("SourcePageId", "TargetPageId");

                    b.HasIndex("TargetPageId")
                        .HasDatabaseName("ix_wiki_page_relations_target_page_id");

                    b.ToTable("wiki_page_relations", (string)null);
                });

            modelBuilder.Entity("DeepWiki.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ChunkIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("chunk_index");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_code");

                    b.Property<bool>("IsImplementation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_implementation");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(1048576)
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repo_url");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<int>("TotalChunks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("total_chunks");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_documents_created_at");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_documents_embedding_cosine")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("RepoUrl")
                        .HasDatabaseName("ix_documents_repo_url");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", b =>
                {
                    b.HasOne("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("ParentPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_wiki_pages_parent_page_id");

                    b.HasOne("DeepWiki.Data.Abstractions.Entities.WikiEntity", "Wiki")
                        .WithMany("Pages")
                        .HasForeignKey("WikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_pages_wiki_id");

                    b.Navigation("ParentPage");

                    b.Navigation("Wiki");
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageRelation", b =>
                {
                    b.HasOne("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", "SourcePage")
                        .WithMany("SourceRelations")
                        .HasForeignKey("SourcePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_page_relations_source_page_id");

                    b.HasOne("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", "TargetPage")
                        .WithMany("TargetRelations")
                        .HasForeignKey("TargetPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_page_relations_target_page_id");

                    b.Navigation("SourcePage");

                    b.Navigation("TargetPage");
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiEntity", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DeepWiki.Data.Abstractions.Entities.WikiPageEntity", b =>
                {
                    b.Navigation("ChildPages");

                    b.Navigation("SourceRelations");

                    b.Navigation("TargetRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
